-- 현재 사용자 계정이 SYS인지 확인
SELECT USER
FROM DUAL;
--==>> SYS

-- 테이블 스페이스 생성
CREATE TABLESPACE TBS_FINAL2TEAM
DATAFILE 'C:\ORACLE_FINAL\FINAL_2TEAM.DBF'
SIZE 20M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
--==>> TABLESPACE TBS_FINAL2TEAM이(가) 생성되었습니다

SELECT *
FROM DBA_TABLESPACES;
/*
TBS_FINAL2TEAM	8192	65536		1	2147483645	2147483645		65536	ONLINE	PERMANENT	LOGGING	NO	LOCAL	SYSTEM	NO	AUTO	DISABLED	NOT APPLY	NO	HOST	NO	
*/

SELECT *
FROM DBA_DATA_FILES;
/*
C:\ORACLE_FINAL\FINAL_2TEAM.DBF	6	TBS_FINAL2TEAM	20971520	2560	AVAILABLE	6	NO	0	0	0	19922944	2432	ONLINE
*/

-- 생성한 테이블 스페이스에 유저 생성
CREATE USER projectors IDENTIFIED BY java002$
DEFAULT TABLESPACE TBS_FINAL2TEAM;
--==>> User PROJECTORS이(가) 생성되었습니다.

-- 유저에 권한 부여(테이블 생성할 수 있도록)
GRANT CREATE TABLE TO projectors;
--==>> Grant을(를) 성공했습니다.

-- 생성된 오라클 사용자 계정(projectors)에
-- 테이블 스페이스(TBL_FINAL)에서 사용할 수 있는 공간(→ 할당량) 제공 (설정)
ALTER USER projectors
QUOTA UNLIMITED ON TBS_FINAL2TEAM;
--==>> User PROJECTORS이(가) 변경되었습니다.

-- 생성된 오라클 사용자 계정의
-- 시스템 관련 권한 조회


SELECT *
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'PROJECTORS';
/*
PROJECTORS	CREATE TABLE	NO
PROJECTORS	UNLIMITED TABLESPACE	NO
*/

-- 생성된 오라클 사용자(POJECTORS)에게 권한 부여
GRANT CREATE TABLE,CONNECT, RESOURCE, UNLIMITED TABLESPACE TO PROJECTORS;
--==>> Grant을(를) 성공했습니다.


GRANT CREATE VIEW TO projectors;


    
