DROP TABLE DEL_REP_COMM CASCADE CONSTRAINTS PURGE;

DROP TABLE COMM_URESULT CASCADE CONSTRAINTS PURGE;

DROP TABLE COMM_PRESULT CASCADE CONSTRAINTS PURGE;

--

DROP TABLE DEL_REP_APPLY CASCADE CONSTRAINTS PURGE;

DROP TABLE APPLY_URESULT CASCADE CONSTRAINTS PURGE;

DROP TABLE APPLY_PRESULT CASCADE CONSTRAINTS PURGE;


DROP TABLE DEL_REP_RECRUIT CASCADE CONSTRAINTS PURGE;

DROP TABLE RECRUIT_URESULT CASCADE CONSTRAINTS PURGE;

DROP TABLE RECRUIT_PRESULT CASCADE CONSTRAINTS PURGE;


DROP TABLE DEL_REP_NOTE CASCADE CONSTRAINTS PURGE;

DROP TABLE NOTE_URESULT CASCADE CONSTRAINTS PURGE;

DROP TABLE NOTE_PRESULT CASCADE CONSTRAINTS PURGE;

/*

Table DEL_REP_COMM이(가) 삭제되었습니다.


Table COMM_URESULT이(가) 삭제되었습니다.


Table COMM_PRESULT이(가) 삭제되었습니다.


Table DEL_REP_APPLY이(가) 삭제되었습니다.


Table APPLY_URESULT이(가) 삭제되었습니다.


Table APPLY_PRESULT이(가) 삭제되었습니다.


Table DEL_REP_RECRUIT이(가) 삭제되었습니다.


Table RECRUIT_URESULT이(가) 삭제되었습니다.


Table RECRUIT_PRESULT이(가) 삭제되었습니다.


Table DEL_REP_NOTE이(가) 삭제되었습니다.


Table NOTE_URESULT이(가) 삭제되었습니다.


Table NOTE_PRESULT이(가) 삭제되었습니다.
*/